-- ============================================================
-- UHS-RIMS Migration v8 - Employee numbers (emp_no)
-- Assigns a sequential employee number 0001..289 in the exact order
-- the client supplied the staff list ("Teaching Final Data"). emp_no is a
-- UNIQUE human-facing identifier; the technical primary key stays the UUID id
-- (swapping the PK would break the view/frontend for no benefit).
-- Rebuilds employees_view to expose emp_no and RE-APPLIES security_invoker
-- (a view reset would otherwise re-open the RLS bypass - see migration v5).
-- Run in Supabase SQL Editor.
-- ============================================================

alter table employees add column if not exists emp_no int;
create unique index if not exists idx_employees_emp_no on employees (emp_no);

-- Number every employee in the given order (matched by unique name).
update employees e
set emp_no = v.no
from (values
  (1,'Dr.S.L.Jagadeesh'),
  (2,'Dr. Thammaiah N.'),
  (3,'Dr. Vishnuvardhana'),
  (4,'Dr. Shankar Meti'),
  (5,'Dr. M. H. Tatagar'),
  (6,'Dr. Gurumurthy S.B.'),
  (7,'Dr. C.N. Hanchinamani'),
  (8,'Dr.M.L.Chavan'),
  (9,'Dr. G.K. Halesh'),
  (10,'Dr. Prabhuling G.'),
  (11,'Dr.R.K.Mesta'),
  (12,'Dr. Krishna H.C.'),
  (13,'Dr. Anjanappa M.'),
  (14,'Dr. Anjaneya Reddy B.'),
  (15,'Dr. J.B.Gopali'),
  (16,'Dr.L.H.Kukanoor'),
  (17,'Dr. Mohammed Farooq'),
  (18,'Dr. Sangappa V. Patil'),
  (19,'Dr. K.R. Vasudeva'),
  (20,'Dr. Ramachandranaik K.'),
  (21,'Dr. Amarananjundeshwara'),
  (22,'Dr. Seetharamu G.K.'),
  (23,'Dr.T.H. Shankarappa'),
  (24,'Dr. Ramachandra R.K.'),
  (25,'Dr. Vijayalaxmi Padaganur'),
  (26,'Dr. P. M. Munnikrishanappa'),
  (27,'Dr. Janardhan G.'),
  (28,'Dr. Shantappa Tirakannavar'),
  (29,'Dr.M.G. Kerutagi'),
  (30,'Dr.B.S.Kulkarni'),
  (31,'Dr. Venkateshalu'),
  (32,'Dr. Fakrudin B.'),
  (33,'Dr. Satish R. Patil'),
  (34,'Dr. Shashikumar S.'),
  (35,'Dr. Basavarajappa M.P.'),
  (36,'Dr.V. M. Ganiger'),
  (37,'Dr.(Mrs) B. C. Patil'),
  (38,'Dr. E. Rajashekhar'),
  (39,'Dr. Sannalaxmanagouda N. Patil'),
  (40,'Dr. Dadapeer A. Peerajade'),
  (41,'Dr. Jholgiker Praveen'),
  (42,'Dr. Iranagouda B. Biradar'),
  (43,'Dr. Bhuvaneshwari G.'),
  (44,'Dr. Anand G. Patil'),
  (45,'Dr. Raveendra S. Jawadagi'),
  (46,'Dr. Kawale Nagendra'),
  (47,'Dr. Rajashekhar M. Hiremath'),
  (48,'Dr. Kantharaju V.'),
  (49,'Dr.A.B. Mastiholi'),
  (50,'Mr.V. D. Gasti'),
  (51,'Dr. Kulpathi Hipparagi'),
  (52,'Dr. Ashok S. Alur'),
  (53,'Dr. Mallikarjun G. Awati'),
  (54,'Dr. R.S. Hiremath'),
  (55,'Dr. D.P. Prakash'),
  (56,'Mr. Rudragouda T. Patil'),
  (57,'Dr. Prabhudev S. Ajjappalavar'),
  (58,'Dr. Venkatesh Hosamani'),
  (59,'Dr. Pushpa P.'),
  (60,'Dr. Aravindkumar J.S.'),
  (61,'Mr. K. Chandan'),
  (62,'Dr. M. Shivapriya'),
  (63,'Dr. Manjunatha G.'),
  (64,'Dr. Tanveer Ahmed'),
  (65,'Dr. Kirankumar K.C.'),
  (66,'Dr. Shivakumar K.M.'),
  (67,'Dr. Moulasab'),
  (68,'Mr. Krishna D. Kurubetta'),
  (69,'Mr. Arunkumar K.T.'),
  (70,'Dr. Shivanand Hongal'),
  (71,'Dr. Dhananjaya B. N.'),
  (72,'Mr. Sreenatha A.'),
  (73,'Dr. Sangeetha C.G.'),
  (74,'Dr. Sadanand K. Mushrif'),
  (75,'Dr. Yekanath Ningappa'),
  (76,'Dr. Gangadhar Narabenchi'),
  (77,'Dr. Anilkumar S'),
  (78,'Dr. Shivayogi Ryavalad'),
  (79,'Mr. R.B.Naik'),
  (80,'Dr. Kiran Nagajjanavar'),
  (81,'Dr. Shobha.S'),
  (82,'Dr. Veena'),
  (83,'Dr. Ratnakar M. Shet'),
  (84,'Dr. Rajkumar M.'),
  (85,'Dr. Harischandra Naik'),
  (86,'Dr. Meenakshi Sood'),
  (87,'Dr. Mangala K.P.'),
  (88,'Dr. Venkat Rao'),
  (89,'Dr. Amruta S. Bhat'),
  (90,'Mrs. Premalatha B.R.'),
  (91,'Dr. Suresh G.J.'),
  (92,'Dr. Maruthi Prasad B.N.'),
  (93,'Dr. Venkatesha S.C.'),
  (94,'Dr. Shankarappa K.S.'),
  (95,'Mr. K. Tulasiram'),
  (96,'Dr. Jayappa J.'),
  (97,'Mr.G.H. Krishnamurthy'),
  (98,'Dr. Mangesh'),
  (99,'Mrs. Lakshmidevamma T.N.'),
  (100,'Dr. B.S. Lakshman Reddy'),
  (101,'Dr. Suhasini Jalawadi'),
  (102,'Dr.Vijaykumar D. Rathod'),
  (103,'Dr. Raghavendra Achari'),
  (104,'Dr. Ganeshgouda Patil'),
  (105,'Mrs. Rajeshwari Nidagundi'),
  (106,'Dr. Sanjeevaraddi G. Reddi'),
  (107,'Dr. Satyanarayan C.'),
  (108,'Dr. Shashikanth Evoor'),
  (109,'Dr. Kirankumar Gorabal'),
  (110,'Dr. Pallavi H.M.'),
  (111,'Dr. Satish D.'),
  (112,'Mr. Manjunath B. Hadimani'),
  (113,'Mr. Yashavantakumar K.H.'),
  (114,'Dr. Vijaykumar B. Narayanapur'),
  (115,'Dr. Jagadishchandra S. Hiremath'),
  (116,'Mr. Praveenkumar B. Naikodi'),
  (117,'Dr. S.K. Jagadeesha'),
  (118,'Dr. Yallesh Kumar H.S'),
  (119,'Dr. Adbul Rahaman M. Nadaf'),
  (120,'Mr. K.R. Lingamurthy'),
  (121,'Dr. Srinivas N.'),
  (122,'Dr. Anil I. Sabarad'),
  (123,'Mr. Basappa Siddappa Kamble'),
  (124,'Dr. Mukund V. Shiragur'),
  (125,'Dr. S.G. Gollagi'),
  (126,'Dr. Sandhyarani Nishyani'),
  (127,'Dr. Sumangala K.'),
  (128,'Ms. Shashikala S. Ruli'),
  (129,'Dr. Ravikumar B.'),
  (130,'Dr. Sheela Rani S.'),
  (131,'Dr. Prasad P.S.'),
  (132,'Dr. Manjula Karadiguddi'),
  (133,'Mr. Sudeesh Kulkarni'),
  (134,'Dr. Veerendra Pratap Singh'),
  (135,'Dr. Ashoka N.'),
  (136,'Dr. Mohan Kumar S.'),
  (137,'Dr. Mamathalakshmi N.'),
  (138,'Dr. Dayamani K.J.'),
  (139,'Dr. Gireesh A. Ganjihal'),
  (140,'Mr. Siddappa R S/O Rachappa'),
  (141,'Dr. Kirtimala Balaji Naik'),
  (142,'Ms. Shoba H.'),
  (143,'Dr. Raghunath R.'),
  (144,'Mr. Ramesh A.P.'),
  (145,'Dr. M. Arun'),
  (146,'Dr. Nagaraja G.'),
  (147,'Mr. Rajeeva H.N.'),
  (148,'Dr. Manjunatha Reddy T.B.'),
  (149,'Dr. Pushpa T.N.'),
  (150,'Dr. Gajanan Kustagi'),
  (151,'Mr. Nataraj K.H.'),
  (152,'Dr. Yogeshappa H.'),
  (153,'Dr. Shashidhar K.R.'),
  (154,'Dr. Manukumar H.R.'),
  (155,'Dr. Harshavardhan M.'),
  (156,'Mr. Pottappa K.'),
  (157,'Dr. Rajesh A.M.'),
  (158,'Dr. Dhananjay P'),
  (159,'Dr. Jyothi Kattegoudar'),
  (160,'Mrs. Anasubai Shivanand Hosagoudar'),
  (161,'Dr. N. Aswathanarayana Reddy'),
  (162,'Mrs. Renuka B. Hirekurubar'),
  (163,'Dr. Nataraj S.K'),
  (164,'Dr. Mahesh Y.S.'),
  (165,'Mr. Imamsaheb Jat'),
  (166,'Dr. Raghunathreddy R.L.'),
  (167,'Dr. Pallavi G.'),
  (168,'Dr. Namitha B. Raut'),
  (169,'Dr. Vinaykumar M.M.'),
  (170,'Dr. Jayashree Ugalat'),
  (171,'Dr. Tippanna K.S.'),
  (172,'Dr. Vikram Appanna'),
  (173,'Dr. Vijaymahantesh'),
  (174,'Dr. Abdul Kareem'),
  (175,'Dr. S M Prasanna'),
  (176,'Dr. Harish B.S.'),
  (177,'Dr. Rashmi H.B.'),
  (178,'Dr. Itigi Prabhakar'),
  (179,'Dr. Padmanabha K'),
  (180,'Dr. Manjunath R.'),
  (181,'Dr. Swetha B.S.'),
  (182,'Dr. Yathindra H.A.'),
  (183,'Dr. G.K. Sadananda'),
  (184,'Dr. Babu A.G.'),
  (185,'Dr. Ambika D.S.'),
  (186,'Dr. Byasigideri Doddabasappa'),
  (187,'Dr. Anand G. Nanjappanavar'),
  (188,'Mr. Sateesh Pattepur'),
  (189,'Dr. Basavarajappa H.R.'),
  (190,'Mr. Shripad Vishweshwar'),
  (191,'Mr. Channabasappa Gangappa Yadav'),
  (192,'Mr. Sayeed Almas R. Mulla'),
  (193,'Dr. Sarvamangala Cholin'),
  (194,'Dr. Ashok'),
  (195,'Dr. Sayeed Wajeed'),
  (196,'Dr. Rudresh D.L.'),
  (197,'Mr. Viresh S/o Mallayya Hiremath'),
  (198,'Mr. Mohammed Abdul Waseem'),
  (199,'Mrs. Vijaya Hosamani'),
  (200,'Dr. Noorulla Haveri'),
  (201,'Dr. Md. Jameel Jhalegar'),
  (202,'Dr. Ramanagowda Hadlageri'),
  (203,'Dr. Deepa Teradal'),
  (204,'Dr. Rekha B. Chittapur'),
  (205,'Dr. Bapurayagouda Patil'),
  (206,'Dr. Chandrashekhar G.S.'),
  (207,'Dr. Sudarshan G.K.'),
  (208,'Dr. S.G. Praveenkumar'),
  (209,'Dr. Dileepkumar Allasaheb Masuthi'),
  (210,'Mr. Prashant A.'),
  (211,'Dr. Y.C. Vishwanath'),
  (212,'Mr. Naveen M. Puttaswamy'),
  (213,'Dr. Sachinkumar T. Nandimath'),
  (214,'Dr. Suvarna Patil'),
  (215,'Mr. Siddanna Thoke'),
  (216,'Mr. Rajendra B N'),
  (217,'Dr. Preetam S.P'),
  (218,'Dr. Santosh Andaneppa Navalur'),
  (219,'Dr. G.K. Ramegowda'),
  (220,'Dr. Arunkumar Bhavidoddy'),
  (221,'Mrs. Jayalaxmi B Pawar'),
  (222,'Dr. Krishna R Yadav'),
  (223,'Dr. Ramachandra V A'),
  (224,'Dr. Chikkanna G S'),
  (225,'Dr. Nagaraja K S'),
  (226,'Dr. Srikanta Prasad D.'),
  (227,'Mr. Chandrakant Kamble'),
  (228,'Dr. Mutthuraju G P'),
  (229,'Dr. Prashant'),
  (230,'Dr. Ambresh'),
  (231,'Dr. Amreen Taj'),
  (232,'Dr. Rajeshwari R.'),
  (233,'Mr. Srinivas P.'),
  (234,'Dr. Pavankumar P.'),
  (235,'Dr. Ashok Kumar'),
  (236,'Dr. Raghavendra Gunnaiah'),
  (237,'Mr. Sreekanth H S'),
  (238,'Dr. Thungamani M.'),
  (239,'Dr. Mahantesh Naika B N'),
  (240,'Dr. Nagaraj Holeyannavar'),
  (241,'Mr. Basavaraj S Padashetti'),
  (242,'Dr. Mala C. Patil'),
  (243,'Dr. Anita R. Gandhe'),
  (244,'Mr. Arunkumar K. Kamble'),
  (245,'Mr. Ramesh'),
  (246,'Dr. Raghavendra'),
  (247,'Dr. Manjunath Hubballi'),
  (248,'Mrs. Netravati'),
  (249,'Dr. Vandana V.'),
  (250,'Dr. Girija B. Endigeri'),
  (251,'Dhanraj P'),
  (252,'Dushanth Olekar'),
  (253,'Annapurna Neeralgi'),
  (254,'Chandalinga'),
  (255,'Dr. Jagadeesha Naika'),
  (256,'Dr. Asha K M'),
  (257,'Dr. Shashidhar Chavan'),
  (258,'Jagadish'),
  (259,'Dr. Lokesha R'),
  (260,'Dr. Suktija M P'),
  (261,'Dr. Nethravathi A Patil'),
  (262,'Dr. Sushma Ishwar Havanur'),
  (263,'Dr. Abhaya Prakash C'),
  (264,'Dr. Sankalpa K. B'),
  (265,'Dr. Srinivas G'),
  (266,'Dr. Lavanya M.N'),
  (267,'Dr. Mohan Naik G'),
  (268,'Dr. Pavan Thejasvi T'),
  (269,'Dr. Shiladhar Pawar'),
  (270,'Kadli Veeresh'),
  (271,'Jhanvi D.R'),
  (272,'Anuradha Rajkumar Wadgave'),
  (273,'Shwetha Hiremath'),
  (274,'Arvind Kumar'),
  (275,'Dr. Ramesh Naik K'),
  (276,'Anjaneya'),
  (277,'Dr. Harish T.'),
  (278,'Dr. Hanumanthaiah R'),
  (279,'Mr. H.P. Hadimani'),
  (280,'Dr. Ramesh S/O Sabayya Naik'),
  (281,'Renuka Muttappanavar'),
  (282,'Dr. Jayaram Naik N'),
  (283,'Dr. Shashidhar Mohan Dodamani'),
  (284,'Chaitra C. Kulkarni'),
  (285,'Prathiksha'),
  (286,'Hanumantrao Jogan'),
  (287,'Dr. Mohana Kumara P'),
  (288,'Raghavendra K.S'),
  (289,'Nanditha G.C')
) as v(no, name)
where e.name = v.name;

-- Rebuild the view so the app can read emp_no.
drop view if exists employees_view;
create view employees_view as
select
  e.id, e.emp_no, e.name, e.designation, e.date_of_birth, e.college_id, c.name as college_name,
  e.email, e.phone,
  e.academic_level, e.discipline, e.present_position, e.working_office, e.place_of_working,
  e.rpc, e.promotion_status,
  e.dt_prof_15, e.dt_prof_14, e.dt_assoc_13a, e.dt_asst_12, e.dt_asst_11, e.dt_asst_10,
  e.dt_instructor, e.dt_service,
  e.created_at
from employees e
left join colleges c on c.id = e.college_id;
alter view employees_view set (security_invoker = true);
